version: '3'
services:
  auth:
    build: ./auth-service
    image: my-auth-micro
    ports:
      - 7070:7070
  
  order:
    build: ./order-service
    image: my-order-micro
    ports:
      - 9090:9090
   
      - auth
      - product

  product:
    build: ./product-service
    image: my-product-micro
    ports:
      - 8080:8080
    
      

  rabbitmq:
    image: rabbitmq
    container_name: kantra
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      
    